### ISSUE TITLE
DPL - proportions qa and qd definition interchanged.

### ISSUE THREAD

**Issue by Prathzee** [aws/amazon-sagemaker-clarify#109]
The formula for the difference in proportions of labels is as follows:

        **DPL = (qa - qd)**

Where:

**qa = na(1)/na** is the proportion of facet a who have an observed label value of 1. For example, the proportion of a middle-aged demographic who get approved for loans. Here na(1) represents the number of members of facet a who get a positive outcome and na the is number of members of facet a.

**qd = nd(1)/nd** is the proportion of facet d who have an observed label value of 1. For example, the proportion of people outside the middle-aged demographic who get approved for loans. Here nd(1) represents the number of members of the facet d who get a positive outcome and nd the is number of members of the facet d.

In the below code,
na and na_pos needs to be for sensitive facet index and ~ operator should be used for nd and nd_pos instead.

Source code:
def DPL(feature: pd.Series, sensitive_facet_index: pd.Series, positive_label_index: pd.Series) -> float:
    require(sensitive_facet_index.dtype == bool, "sensitive_facet_index must be of type bool")
    require(positive_label_index.dtype == bool, "label_index must be of type bool")
    na = len(feature[~sensitive_facet_index])
    nd = len(feature[sensitive_facet_index])
    na_pos = len(feature[~sensitive_facet_index & positive_label_index])
    nd_pos = len(feature[sensitive_facet_index & positive_label_index])
    if na == 0:
        raise ValueError("Negative facet set is empty.")
    if nd == 0:
        raise ValueError("Facet set is empty.")
    qa = na_pos / na
    qd = nd_pos / nd
    dpl = qa - qd
    return dpl

**Comment by Prathzee** [comment]
Same issue with Disparate Impact formula -
The formula for the ratio of proportions of the predicted labels:

        DI = q'd/q'a

Where:

q'a = n'a(1)/na is the predicted proportion of facet a who get a positive outcome of value 1. In our example, the proportion of a middle-aged facet predicted to get granted a loan. Here n'a(1) represents the number of members of facet a who get a positive predicted outcome and na the is number of members of facet a.

q'd = n'd(1)/nd is the predicted proportion of facet d a who get a positive outcome of value 1. In our example, a facet of older and younger people predicted to get granted a loan. Here n'd(1) represents the number of members of facet d who get a positive predicted outcome and nd the is number of members of facet d.

Here,
na needs to be **len(feature[sensitive_facet_index])** and not **len(feature[~sensitive_facet_index])**

Source code:
    na1hat = len(feature[positive_predicted_label_index & (~sensitive_facet_index)])
    na = len(feature[~sensitive_facet_index])
    if na == 0:
        raise ValueError("Negated facet set is empty")
    qa = na1hat / na
    nd1hat = len(feature[positive_predicted_label_index & sensitive_facet_index])
    nd = len(feature[sensitive_facet_index])
    if nd == 0:
        raise ValueError("Facet set is empty")
    qd = nd1hat / nd
    return divide(qd, qa)

**Comment by keerthanvasist** [comment]
Thank you for reaching out, and taking the effort to read through our source code @Prathzee. 

If you look at the [AWS documentation for [SageMaker Clarify](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-configure-processing-jobs.html), you will that `facet` is defined as below - 

>""facet" – (Optional) A list of features that are sensitive attributes, referred to as facets, to be used for bias metrics in the form of pairs to include the following:

>>"name_or_index" – Facet column name or index.

>>"value_or_threshold" – (Optional) List of values or threshold that the facet column can take which indicates the sensitive group, i.e. the group that is used to measure bias against. If not provided, bias metrics are computed as one group versus all for every unique value. If the facet column is numeric this threshold value is applied as the lower bound to select the sensitive group."


With that in perspective, the `sensitive_facet_index` is an index that is true for members of the facet column that are "sensitive".  `qa`(or `na`) refers to the number of members of the facet who are "advantaged" (read ~sensitive), and `qd`(or `nd`) refers to the number of members of the facet who are advantaged. 

Let me know if that helps. I am closing this ticket for now, but feel free to reopen it.
