### ISSUE TITLE
How can i use it for forecasting model or the regression model

### ISSUE THREAD

**Issue by j-sieger** [aws/amazon-sagemaker-clarify#116]
Hi Team,
Please let me know how can i use it for forecasting model

```label_column = report.LabelColumn(name='{}'.format(output_name), data=output_col, positive_label_values=['{}'.format(output_name)])```
in the above line what value can i pass in `positive_label_values`.
for classification problem i can pass like 

`label_column = report.LabelColumn(output_name, output_col, [1])`
or 
`label_column = report.LabelColumn(output_name, output_col, ['yes'])`

but for in my case **temperature** is the `target` column
Do please let me how config the `label_column` and also the below line.

`bias_report = report.bias_report(train_df, facet_column, label_column, stage_type=report.StageType.PRE_TRAINING, group_variable= output_col)`

**Comment by malhotra18** [comment]
1. `positive_label_values` always indicates what values are considered positive. For regression, this is a threshold (so it will be a single value). For classification, it will be a list of values -  all values that are considered positive.
2. `label_column` should be the target column. The true targets. Similarly predicted targets can be passed in `predicted_label_column`
