### ISSUE TITLE
Clarify Job Failed due to Predicted Label Column series datatype is not the same as Label Column series

### ISSUE THREAD

**Issue by jessieweiyi** [aws/amazon-sagemaker-clarify#131]
Hi, 

I am using SageMakerClarifyProcessor to generate analysis reports for a XGBoost Binary Classification Model. However, the job failed due to *Predicted Label Column series datatype is not the same as Label Column series*.

The log output is:
```
1663079368252 | [ 2022-09-13T14:29:28.252Z ] 2022-09-13 14:29:23,993 Errors occurred when analyzing your data. Please check CloudWatch logs for more details.

1663079368252 | [ 2022-09-13T14:29:28.252Z ] 2022-09-13 14:29:23,993 exit_message: Customer Error: Predicted Label Column series datatype is not the same as Label Column series

1663079368252 | [ 2022-09-13T14:29:28.252Z ] 2022-09-13 14:29:23,992 Column None with data uniqueness fraction 0.00029424746211563924 is classifed as a CATEGORICAL column

1663079368252 | [ 2022-09-13T14:29:28.252Z ] 2022-09-13 14:29:23,951 Column STATUS with data uniqueness fraction 0.00029424746211563924 is classifed as a CONTINUOUS column
```

The data is something like:
```
0,0,3698911.49,89.12865,1,10,0,937296,1,0,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
0,0,1953000,89.30876,1,7.5,0,1116000,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
```

The first column is the predict label, and the second column is the ground truth label. 

Any suggestions that I can get around with this issue given that we do not have control on how sagemaker process the datatype?

**Comment by keerthanvasist** [comment]
This seems strange. Can you please share sample data with us so that I can check? It would also be useful to see the analysis config along with it.

**Comment by jessieweiyi** [comment]
Hi @keerthanvasist
 
I figured out the error is due to the dType of the binary columns. It is parsed as float. And the prediction is int. I have to parse all the binary columns as str to make their dtype as int so that the Clarify job can continue
