### ISSUE TITLE
Bias mitigation and fairness boosting in multi class classification use case

### ISSUE THREAD

**Issue by pradeepdev-1995** [aws/amazon-sagemaker-clarify#137]
Is Amazon-SageMaker-clarify support mitigating bias and improving fairness in multi-class classification problems?
If so please provide an example of doing the same in a sample multi-class classification dataset.

**Comment by xgchena** [comment]
Thank you for reaching out to us. 

If you mean the amazon-sagemaker-clarify library (this repo). The library supports detecting potential bias during data preparation and in trained model, but it does not support bias mitigation methods yet.

To detect bias for multi-class classification problems: when you call the [bias_report](https://github.com/aws/amazon-sagemaker-clarify/blob/9a47250d3e640679ce873acc4ac2374c8bd2b6a2/src/smclarify/bias/report.py#L357) function to compute bias metrics, you need to assign a [LabelColumn](https://github.com/aws/amazon-sagemaker-clarify/blob/9a47250d3e640679ce873acc4ac2374c8bd2b6a2/src/smclarify/bias/report.py#L46) object to the `label_column` parameter. The object should be initialized with the label column `name`, and the label data `series`, and the `positive_label_values`. If the label is multi-class, the `positive_label_values` parameter is a list of label values that are favorable to a demographic group observed in a sample. 

E.g., if the label column of your dataset has three classes "A", "B" and "C", and samples that have label value "A" or "B" designates positive result, then assign `["A", "B"]` to the parameter,

```
    df = pd.read_csv("dataset.csv")
    label = LabelColumn(
        name=label_name,
        series=df[label_name],
        positive_label_values=["A", "B"],
    )

```

FYI: SageMaker Clarify uses [these terms](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-detect-data-bias.html) to discuss bias and fairness, and here are the definition of [pretraining bias metrics](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-detect-data-bias.html) and [posttraining bias metrics](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-measure-post-training-bias.html).
 
If you have any additional questions or concerns regarding the topic, we suggest that you post your queries to the AWS re:Post forum. It is a great platform to get support from the community and our experts. Please remember to include the tag [Amazon SageMaker Clarify](https://repost.aws/tags/TAlEAotjPdR02YRB_rZdkGng/amazon-sage-maker-clarify) in your post to help us better understand your query and provide you with the most relevant assistance. We hope this helps and look forward to hearing from you on the forum.

**Comment by goswamig** [comment]
@pradeepdev-1995 Do you have any particular technique in mind that you want to be present in Clarify for bias mitigation point of view ?
